#!/bin/bash
echo "Here are some tips on enumeration (username, passwords, etc)"
echo ""
echo "	(1) Username enumeration with ffuf"
echo "		ffuf -w /usr/share/wordlists/SecLists/Usernames/Names/names.txt -X POST -d \"username=FUZZ\"" -H \"Content-Type: application/x-www-form-urlencoded\" -u http://<url> -mr \"username already exists\"
echo "		where:"
echo "			-X : request method (GET by default)"
echo "			-d : data to send"
echo "			-H : adding additional headers"
echo "			-u : the url"
echo "			-mr : the text on the page we are looking for when successful"
echo ""
echo "	(2) Password brute forcing with found users"
echo "		ffuf w users.txt:W1,/home/adam/SecLists/Passwords/Common-Credentials/10-million-password-list-top-100.txt:W2 -X POST -d \"username=W1&password=W2\" -H \"Content-Type: application/x-www-form-urlencoded\" -u http://<url> -fc 200"
echo "		where:"
echo "			-fc : the successful code we are looking for"
